set(_CATKIN_CURRENT_PACKAGE "option_srvs")
set(option_srvs_VERSION "0.0.0")
set(option_srvs_MAINTAINER "zwhy2022 <zwhy2022@todo.todo>")
set(option_srvs_PACKAGE_FORMAT "2")
set(option_srvs_BUILD_DEPENDS "roscpp" "rosmsg" "rospy" "message_generation")
set(option_srvs_BUILD_EXPORT_DEPENDS "roscpp" "rosmsg" "rospy")
set(option_srvs_BUILDTOOL_DEPENDS "catkin")
set(option_srvs_BUILDTOOL_EXPORT_DEPENDS )
set(option_srvs_EXEC_DEPENDS "roscpp" "rosmsg" "rospy" "message_runtime")
set(option_srvs_RUN_DEPENDS "roscpp" "rosmsg" "rospy" "message_runtime")
set(option_srvs_TEST_DEPENDS )
set(option_srvs_DOC_DEPENDS )
set(option_srvs_URL_WEBSITE "")
set(option_srvs_URL_BUGTRACKER "")
set(option_srvs_URL_REPOSITORY "")
set(option_srvs_DEPRECATED "")