set(_CATKIN_CURRENT_PACKAGE "server")
set(server_VERSION "0.0.0")
set(server_MAINTAINER "zwhy2022 <zwhy2022@todo.todo>")
set(server_PACKAGE_FORMAT "2")
set(server_BUILD_DEPENDS "roscpp" "rosmsg" "rospy" "option_srvs")
set(server_BUILD_EXPORT_DEPENDS "roscpp" "rosmsg" "rospy" "option_srvs")
set(server_BUILDTOOL_DEPENDS "catkin")
set(server_BUILDTOOL_EXPORT_DEPENDS )
set(server_EXEC_DEPENDS "roscpp" "rosmsg" "rospy" "option_srvs")
set(server_RUN_DEPENDS "roscpp" "rosmsg" "rospy" "option_srvs")
set(server_TEST_DEPENDS )
set(server_DOC_DEPENDS )
set(server_URL_WEBSITE "")
set(server_URL_BUGTRACKER "")
set(server_URL_REPOSITORY "")
set(server_DEPRECATED "")